# Generated by Django 4.2.21 on 2025-06-25 16:03

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gestcaptur.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('gestor', 'Gestor'), ('fotografo', 'Fotógrafo'), ('coordenador', 'Coordenador')], default='fotografo', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', gestcaptur.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fot', models.CharField(max_length=100, verbose_name='FOT')),
                ('data', models.DateField(verbose_name='Data do Evento')),
                ('instituicao', models.CharField(blank=True, max_length=200, verbose_name='Instituição')),
                ('curso', models.CharField(blank=True, max_length=200, verbose_name='Curso')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('tipo_evento', models.CharField(blank=True, max_length=100, verbose_name='Tipo Evento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('local', models.CharField(blank=True, max_length=200, verbose_name='Local')),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereço completo')),
                ('horario', models.CharField(blank=True, max_length=100, verbose_name='Horário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Início'), ('iniciado', 'Em Andamento'), ('finalizado', 'Finalizado')], default='pendente', max_length=20)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_fim', models.DateTimeField(blank=True, null=True)),
                ('coordenador_tambem_fotografo', models.BooleanField(default=False, help_text='Marque se o coordenador deste evento também atuará como fotógrafo.')),
                ('coordenador', models.ForeignKey(blank=True, limit_choices_to={'role': 'coordenador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_coordenados', to=settings.AUTH_USER_MODEL)),
                ('fotografos', models.ManyToManyField(blank=True, related_name='eventos_atribuidos', to=settings.AUTH_USER_MODEL, verbose_name='Fotógrafos')),
            ],
            options={
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessaoFotografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_fotos', models.IntegerField(default=0)),
                ('numero_cartao', models.CharField(blank=True, max_length=50, null=True)),
                ('inicio_sessao', models.DateTimeField(auto_now_add=True)),
                ('fim_sessao', models.DateTimeField(blank=True, null=True)),
                ('finalizado_fotografo', models.BooleanField(default=False)),
                ('finalizado_evento', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_fotograficas', to='gestcaptur.evento')),
                ('fotografo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('endereco', models.CharField(blank=True, max_length=300, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone_fixo', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsapp_pai', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsapp_mae', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_parente', models.CharField(blank=True, max_length=200, null=True)),
                ('grau_parentesco', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_parente', models.CharField(blank=True, max_length=20, null=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ident', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='event_photos/')),
                ('card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='gestcaptur.evento')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos_taken_by_aluno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
