# Generated by Django 4.2.21 on 2025-06-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestcaptur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cadastro_completo',
            field=models.BooleanField(default=False, verbose_name='Cadastro Completo'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_ultimo_email',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Email Enviado'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='tentativas_email',
            field=models.IntegerField(default=0, verbose_name='Tentativas de Email'),
        ),
    ]
