# Generated by Django 4.2.21 on 2026-01-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestcaptur', '0002_aluno_cadastro_completo_aluno_data_ultimo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='status_comparecimento',
            field=models.CharField(choices=[('presente', 'Presente'), ('faltoso', 'Faltoso')], default='presente', max_length=10, verbose_name='Status Comparecimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='whatsapp',
            field=models.CharField(max_length=20, verbose_name='WhatsApp'),
        ),
    ]
