# Generated by Django 4.2.21 on 2026-01-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestcaptur', '0003_aluno_status_comparecimento_alter_aluno_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('gestor', 'Gestor'), ('fotografo', 'Fotógrafo'), ('coordenador', 'Coordenador'), ('pesquisa', 'Pesquisa')], default='fotografo', max_length=20),
        ),
    ]
