# Generated by Django 4.2.21 on 2026-02-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestcaptur', '0004_alter_usuario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='para_selfie',
            field=models.BooleanField(default=False, help_text='Marque para permitir que alunos capturem selfie pública antes do cadastro.', verbose_name='Evento para selfie?'),
        ),
    ]
