# Generated by Django 4.2.21 on 2026-05-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestcaptur", "0005_evento_para_selfie"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="codigo_turma",
            field=models.CharField(
                blank=True,
                help_text="Código identificador da turma (ex: 2024-A, EM-001)",
                max_length=50,
                null=True,
                verbose_name="Código da Turma",
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="selfie_realizada",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o formando capturou a selfie obrigatória",
                verbose_name="Selfie Realizada",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="codigo_turma",
            field=models.CharField(
                blank=True,
                help_text="Código único da turma (ex: 2024-A, EM-001). Aplicado automaticamente a todos os alunos.",
                max_length=50,
                null=True,
                verbose_name="Código da Turma",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="permite_importacao_nomes",
            field=models.BooleanField(
                default=False,
                help_text="Marque para permitir importação de lista de nomes via XLSX",
                verbose_name="Importar nomes?",
            ),
        ),
    ]
