# Generated by Django 4.2.21 on 2026-05-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestcaptur", "0006_aluno_codigo_turma_aluno_selfie_realizada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="uuid",
            field=models.CharField(
                blank=True,
                help_text="Identificador único para compartilhamento seguro",
                max_length=36,
                null=True,
                unique=True,
                verbose_name="UUID do Evento",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="whatsapp",
            field=models.CharField(max_length=20),
        ),
    ]
