# Generated by Django 4.2.21 on 2026-05-20 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestcaptur", "0007_evento_uuid_alter_aluno_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="parceiros",
            field=models.ManyToManyField(
                blank=True,
                help_text="Selecione os parceiros que terão acesso de leitura a este evento",
                limit_choices_to={"role": "parceiro"},
                related_name="eventos_como_parceiro",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Parceiros com Acesso",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="role",
            field=models.CharField(
                choices=[
                    ("gestor", "Gestor"),
                    ("fotografo", "Fotógrafo"),
                    ("coordenador", "Coordenador"),
                    ("pesquisa", "Pesquisa"),
                    ("parceiro", "Parceiro"),
                ],
                default="fotografo",
                max_length=20,
            ),
        ),
    ]
