# Generated by Django 4.2.21 on 2026-05-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestcaptur', '0008_evento_parceiros_alter_usuario_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(help_text='CPF do formando (obrigatório e único)', max_length=14, verbose_name='CPF'),
        ),
        migrations.AddConstraint(
            model_name='aluno',
            constraint=models.UniqueConstraint(fields=('evento', 'cpf'), name='unique_cpf_per_evento', violation_error_message='Já existe um cadastro com este CPF neste evento.'),
        ),
    ]
