# Generated by Django 4.2.21 on 2026-08-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestcaptur", "0009_remove_cpf_global_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="codigo_turma",
            field=models.CharField(
                blank=True,
                help_text="Código identificador da turma (ex: 2024-A, EM-001)",
                max_length=100,
                null=True,
                verbose_name="Código da Turma",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="codigo_turma",
            field=models.CharField(
                blank=True,
                help_text="Código único da turma (ex: 2024-A, EM-001). Aplicado automaticamente a todos os alunos.",
                max_length=100,
                null=True,
                verbose_name="Código da Turma",
            ),
        ),
    ]
