# Generated by Django 4.2.21 on 2026-08-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestcaptur", "0012_event_role_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={
                "permissions": (
                    ("ver_guia_grade", "Pode ver a guia Grade do dashboard"),
                    ("ver_guia_andamento", "Pode ver a guia Em Andamento do dashboard"),
                    (
                        "ver_guia_finalizados",
                        "Pode ver a guia Finalizados do dashboard",
                    ),
                    (
                        "ver_guia_fichas_fotos",
                        "Pode ver a guia Fichas e Fotos do dashboard",
                    ),
                    ("ver_guia_resumo", "Pode ver a guia Resumo do dashboard"),
                )
            },
        ),
        migrations.AlterField(
            model_name="usuario",
            name="role",
            field=models.CharField(
                choices=[
                    ("gestor", "Gestor"),
                    ("fotografo", "Fotógrafo"),
                    ("coordenador", "Coordenador"),
                    ("pesquisa", "Pesquisa"),
                    ("parceiro", "Parceiro"),
                    ("personalizado", "Personalizado (acesso via permissões do grupo)"),
                ],
                default="fotografo",
                max_length=20,
            ),
        ),
    ]
