# Generated by Django 4.2.21 on 2026-09-02 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gestcaptur", "0013_role_personalizado_e_permissoes_dashboard"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={
                "permissions": (
                    ("ver_guia_grade", "Pode ver a guia Grade do dashboard"),
                    ("ver_guia_andamento", "Pode ver a guia Em Andamento do dashboard"),
                    (
                        "ver_guia_finalizados",
                        "Pode ver a guia Finalizados do dashboard",
                    ),
                    (
                        "ver_guia_fichas_fotos",
                        "Pode ver a guia Fichas e Fotos do dashboard",
                    ),
                    ("ver_guia_resumo", "Pode ver a guia Resumo do dashboard"),
                    (
                        "gerenciar_roles",
                        "Pode gerenciar roles e permissões (menu Usuários)",
                    ),
                    (
                        "ver_botao_compartilhar_formandos",
                        "Pode ver o botão Compartilhar Link/QRCode (painel de formandos)",
                    ),
                    (
                        "ver_botao_parceiros_formandos",
                        "Pode ver o botão Parceiros (painel de formandos)",
                    ),
                )
            },
        ),
    ]
