# Generated by Django 4.2.21 on 2026-09-25 23:13

from django.db import migrations, models
import gestcaptur.models


class Migration(migrations.Migration):
    dependencies = [
        ("gestcaptur", "0015_adicionar_permissao_pode_criar_parceiro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="foto",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=gestcaptur.models.caminho_foto_aluno,
            ),
        ),
    ]
